build.sbt
src/main/scala/me/dfdx/metarank/Main.scala
src/main/scala/me/dfdx/metarank/config/Config.scala
src/test/resources/config/config.invalid.invalidyaml.yml
src/test/resources/config/config.invalid.noschema.yml
src/test/resources/config/config.valid.yml
src/test/scala/me/dfdx/metarank/config/ConfigLoadingTest.scala

With basic structure for schema, feedback types and network config.

yaml config support

---

build.sbt

As xgboost pulls them for some weird reason

remove transitive dependency on akka and scala-compiler

---

build.sbt
src/main/scala/me/dfdx/metarank/Main.scala
src/main/scala/me/dfdx/metarank/config/CommandLineConfig.scala
src/main/scala/me/dfdx/metarank/config/Config.scala
src/test/scala/me/dfdx/metarank/config/CommandLineConfigTest.scala

add command line args support

---

api/build.sbt
api/src/main/scala/me/dfdx/metarank/ApiMain.scala
api/src/main/scala/me/dfdx/metarank/model/RankRequest.scala
api/src/main/scala/me/dfdx/metarank/model/RankResponse.scala
api/src/main/scala/me/dfdx/metarank/services/RankService.scala
api/src/test/scala/me/dfdx/metarank/services/RankServiceTest.scala
build.sbt
core/build.sbt
core/src/main/scala/me/dfdx/metarank/model/Event.scala
core/src/main/scala/me/dfdx/metarank/model/ItemId.scala
core/src/main/scala/me/dfdx/metarank/model/RequestId.scala
core/src/main/scala/me/dfdx/metarank/model/SessionId.scala
core/src/main/scala/me/dfdx/metarank/model/Timestamp.scala
core/src/main/scala/me/dfdx/metarank/model/UserId.scala
doc/02_tech_overview.md
ingest/build.sbt
ingest/src/main/scala/me/dfdx/metarank/IngestMain.scala
ingest/src/main/scala/me/dfdx/metarank/RestIOApp.scala
ingest/src/test/scala/me/dfdx/metarank/service/HealthcheckServiceTest.scala
ingest/src/test/scala/me/dfdx/metarank/service/IngestServiceTest.scala
ingest/src/test/scala/me/dfdx/metarank/service/ServiceRouteTest.scala
project/Deps.scala

implement draft ranking API spec

---

api/src/main/scala/me/dfdx/metarank/model/RankRequest.scala
api/src/test/scala/me/dfdx/metarank/services/RankServiceTest.scala
core/src/main/scala/me/dfdx/metarank/model/Event.scala
core/src/main/scala/me/dfdx/metarank/model/Scope.scala
doc/02_tech_overview.md
ingest/src/test/scala/me/dfdx/metarank/service/IngestServiceTest.scala

add user/session to interaction event

---

core/build.sbt
core/src/main/scala/me/dfdx/metarank/aggregation/state/State.scala
core/src/main/scala/me/dfdx/metarank/config/Config.scala
core/src/main/scala/me/dfdx/metarank/config/FeatureConfig.scala
core/src/main/scala/me/dfdx/metarank/config/StoreConfig.scala
core/src/main/scala/me/dfdx/metarank/store/NullStore.scala
core/src/main/scala/me/dfdx/metarank/store/RedisStore.scala
core/src/main/scala/me/dfdx/metarank/store/Store.scala
core/src/test/resources/config/config.valid.yml
core/src/test/scala/me/dfdx/metarank/config/FeatureConfigTest.scala
core/src/test/scala/me/dfdx/metarank/config/StoreConfigTest.scala
core/src/test/scala/me/dfdx/metarank/store/HeapBytesStoreTest.scala
core/src/test/scala/me/dfdx/metarank/store/RedisStoreTest.scala
core/src/test/scala/me/dfdx/metarank/store/StoreTestSuite.scala

add redis store (and store config section)

---

core/src/main/scala/me/dfdx/metarank/aggregation/Scope.scala
core/src/main/scala/me/dfdx/metarank/config/Config.scala
core/src/main/scala/me/dfdx/metarank/model/Featurespace.scala
core/src/main/scala/me/dfdx/metarank/store/HeapBytesStore.scala
core/src/main/scala/me/dfdx/metarank/store/HeapStore.scala
core/src/main/scala/me/dfdx/metarank/store/RedisStore.scala
core/src/test/resources/config/config.valid.yml
core/src/test/scala/me/dfdx/metarank/config/ConfigLoadingTest.scala
core/src/test/scala/me/dfdx/metarank/feature/CountFeatureTest.scala
core/src/test/scala/me/dfdx/metarank/store/HeapBytesStoreTest.scala
core/src/test/scala/me/dfdx/metarank/store/HeapStoreTest.scala
core/src/test/scala/me/dfdx/metarank/store/RedisStoreTest.scala
core/src/test/scala/me/dfdx/metarank/store/StoreTestSuite.scala

add support for multiple featurespaces

---

api/src/main/scala/me/dfdx/metarank/ApiMain.scala
core/src/main/scala/me/dfdx/metarank/aggregation/Aggregation.scala
core/src/main/scala/me/dfdx/metarank/config/Config.scala
core/src/main/scala/me/dfdx/metarank/config/StoreConfig.scala
core/src/main/scala/me/dfdx/metarank/store/RedisStore.scala
core/src/main/scala/me/dfdx/metarank/store/Store.scala
core/src/test/resources/config/config.valid.yml
core/src/test/scala/me/dfdx/metarank/aggregation/CountAggregationTest.scala
core/src/test/scala/me/dfdx/metarank/config/StoreConfigTest.scala
ingest/src/main/scala/me/dfdx/metarank/Aggregations.scala
ingest/src/main/scala/me/dfdx/metarank/IngestMain.scala
ingest/src/main/scala/me/dfdx/metarank/RestIOApp.scala
ingest/src/main/scala/me/dfdx/metarank/services/IngestService.scala
ingest/src/test/scala/me/dfdx/metarank/AggregationsTest.scala
ingest/src/test/scala/me/dfdx/metarank/TestAggregation.scala
ingest/src/test/scala/me/dfdx/metarank/service/IngestServiceTest.scala

add basic ingestion pipeline

---

core/src/main/scala/me/dfdx/metarank/aggregation/Aggregation.scala
core/src/main/scala/me/dfdx/metarank/aggregation/CountAggregation.scala
core/src/main/scala/me/dfdx/metarank/aggregation/ItemMetadataAggregation.scala
core/src/main/scala/me/dfdx/metarank/aggregation/Scope.scala
core/src/main/scala/me/dfdx/metarank/config/AggregationConfig.scala
core/src/main/scala/me/dfdx/metarank/feature/CountFeature.scala
core/src/main/scala/me/dfdx/metarank/model/Field.scala
core/src/main/scala/me/dfdx/metarank/store/state/StateDescriptor.scala
core/src/main/scala/me/dfdx/metarank/store/state/codec/Codec.scala
core/src/main/scala/me/dfdx/metarank/store/state/codec/KeyCodec.scala
core/src/test/resources/config/config.valid.yml
core/src/test/scala/me/dfdx/metarank/aggregation/ItemMetadataAggregationTest.scala
core/src/test/scala/me/dfdx/metarank/config/ConfigLoadingTest.scala
core/src/test/scala/me/dfdx/metarank/model/TestItemMetadataEvent.scala
core/src/test/scala/me/dfdx/metarank/store/StoreTestSuite.scala
core/src/test/scala/me/dfdx/metarank/store/state/codec/CodecDerivationTest.scala
core/src/test/scala/me/dfdx/metarank/store/state/codec/KeyCodecDerivationTest.scala

Product metadata store

---

core/src/main/scala/me/dfdx/metarank/aggregation/Aggregation.scala
core/src/main/scala/me/dfdx/metarank/aggregation/ItemMetadataAggregation.scala
core/src/main/scala/me/dfdx/metarank/config/Config.scala
core/src/main/scala/me/dfdx/metarank/model/Field.scala
core/src/main/scala/me/dfdx/metarank/model/Nel.scala
core/src/main/scala/me/dfdx/metarank/model/SchemaMismatchError.scala
core/src/test/resources/config/config.valid.yml
core/src/test/scala/me/dfdx/metarank/aggregation/ItemMetadataAggregationTest.scala
core/src/test/scala/me/dfdx/metarank/feature/QueryItemMatchFeatureTest.scala
ingest/src/main/scala/me/dfdx/metarank/Aggregations.scala

add check to validate item metadata over field schema

---

README.md
doc/01_intro.md
doc/02_tech_overview.md

- cleared some language
- rephrased items

Documentation update

---

.gitattributes
src/test/resources/ranklens/events.jsonl.gz
src/test/scala/ai/metarank/util/RanklensDatasetGenerator.scala

Just a converter from Ranklens format to the Metarank event format.

support for reading ranklens dataset

---

project/Deps.scala
src/main/scala/ai/metarank/FeatureMapping.scala
src/main/scala/ai/metarank/feature/BooleanFeature.scala
src/main/scala/ai/metarank/feature/InteractedWithFeature.scala
src/main/scala/ai/metarank/feature/MetaFeature.scala
src/main/scala/ai/metarank/feature/NumberFeature.scala
src/main/scala/ai/metarank/feature/RateFeature.scala
src/main/scala/ai/metarank/feature/StringFeature.scala
src/main/scala/ai/metarank/feature/WordCountFeature.scala
src/main/scala/ai/metarank/flow/ClickthroughJoin.scala
src/main/scala/ai/metarank/flow/DatasetSink.scala
src/main/scala/ai/metarank/flow/EventStateJoin.scala
src/main/scala/ai/metarank/mode/TypeInfos.scala
src/main/scala/ai/metarank/mode/bootstrap/Bootstrap.scala
src/main/scala/ai/metarank/model/Clickthrough.scala
src/main/scala/ai/metarank/model/EventState.scala
src/main/scala/ai/metarank/model/FeatureScope.scala
src/test/scala/ai/metarank/e2e/RanklensTest.scala
src/test/scala/ai/metarank/e2e/StatefulFeatureTest.scala
src/test/scala/ai/metarank/feature/InteractedWithFeatureTest.scala
src/test/scala/ai/metarank/feature/RateFeatureTest.scala
src/test/scala/ai/metarank/flow/DatasetSinkTest.scala

So there are no hacks in InteractedWithFeature

support stateful write generators

---

README.md
doc/tutorial_ranklens.md

- restructured the doc a bit
- updated the link in main readme

Updated tutorial doc

---

doc/xx_api_schema.md
doc/xx_event_schema.md

Updated documentation for events and API

Docs update

---

.gitignore
build.sbt
project/Deps.scala
src/main/scala/ai/metarank/mode/inference/FeedbackFlow.scala
src/main/scala/ai/metarank/mode/inference/Inference.scala
src/main/scala/ai/metarank/mode/inference/InferenceCmdline.scala
src/main/scala/ai/metarank/mode/inference/RedisEndpoint.scala
src/main/scala/ai/metarank/mode/train/Train.scala
src/main/scala/ai/metarank/mode/upload/Upload.scala

So you dont need to start redis to play with metarank

implement embedded redis store for local runs

---

README.md
build.sbt
doc/docker.md
src/main/scala/ai/metarank/Main.scala

So you can do `sbt docker:publishLocal` and it will build a fully functional container. The task is used for publishing official images to Docker Hub `https://hub.docker.com/u/metarank`.

docker container building task

---

build.sbt
deploy/k8s-manifests/api.yml
doc/deploy/README.md
doc/deploy/aws.md
doc/deploy/cli-options.md
doc/deploy/docker.md
src/main/scala/ai/metarank/mode/FileLoader.scala
src/main/scala/ai/metarank/mode/FlinkS3Configuration.scala
src/main/scala/ai/metarank/mode/bootstrap/Bootstrap.scala
src/main/scala/ai/metarank/mode/bootstrap/BootstrapCmdline.scala
src/main/scala/ai/metarank/mode/inference/FlinkMinicluster.scala
src/main/scala/ai/metarank/mode/inference/Inference.scala
src/main/scala/ai/metarank/mode/inference/InferenceCmdline.scala
src/main/scala/ai/metarank/mode/inference/RedisEndpoint.scala
src/main/scala/ai/metarank/mode/train/Train.scala
src/main/scala/ai/metarank/mode/train/TrainCmdline.scala
src/main/scala/ai/metarank/mode/upload/Upload.scala
src/main/scala/ai/metarank/mode/upload/UploadCmdline.scala
src/test/scala/ai/metarank/mode/FlinkS3ConfigurationTest.scala
src/test/scala/ai/metarank/mode/InferenceCmdlineTest.scala

* add support for env variable CLI overrides
* draft version of k8s manifests
* S3 credentials loading for AWS

K8s integration

---

build.sbt
doc/deploy/docker.md
project/FlinkMergeStrategy.scala

A fix for https://github.com/metarank/metarank/issues/308

fix issue with s3 classpath conflict

---

.github/workflows/scala.yml

To make sure that all the code coming in PRs is properly formatted

add scalafmt check to ci

---

src/main/scala/ai/metarank/config/Config.scala
src/test/scala/ai/metarank/config/ConfigTest.scala

fixes https://github.com/metarank/metarank/issues/217

do not allow empty/dupe features

---

build.sbt

a fix for https://github.com/metarank/metarank/issues/320

add libgomp1 to docker image

---

doc/features/generic.md
doc/features/scalar.md
doc/features/user-session.md
doc/xx_feature_extractors.md
src/main/scala/ai/metarank/feature/BooleanFeature.scala
src/main/scala/ai/metarank/feature/InteractedWithFeature.scala
src/main/scala/ai/metarank/feature/NumberFeature.scala
src/main/scala/ai/metarank/feature/StringFeature.scala
src/main/scala/ai/metarank/feature/WordCountFeature.scala

List in docs which types are expected by each feature extractor, add logging in case if expected type is not matching the supplied one

Field type checking

---

src/main/scala/ai/metarank/mode/inference/FeatureStoreResource.scala
src/main/scala/ai/metarank/mode/inference/Inference.scala
src/main/scala/ai/metarank/mode/inference/api/RankApi.scala
src/test/scala/ai/metarank/api/RankApiTest.scala
src/test/scala/ai/metarank/e2e/RanklensTest.scala
src/test/scala/ai/metarank/mode/RankApiTest.scala

Fixes a most common crash on demo.metarank.ai (see https://github.com/metarank/metarank/issues/318 for details)

reconnect to store on failure

---

doc/features/text.md
doc/xx_feature_extractors.md
src/main/scala/ai/metarank/FeatureMapping.scala
src/main/scala/ai/metarank/feature/FieldMatchFeature.scala
src/main/scala/ai/metarank/model/FeatureSchema.scala
src/test/scala/ai/metarank/feature/FieldMatchFeatureTest.scala

fixes https://github.com/metarank/metarank/issues/328

Field match extractor

---

.github/workflows/scala.yml
build.sbt

Looks like https://github.com/metarank/metarank/issues/342 is caused by the following line in build.sbt:
```scala
dockerPermissionStrategy := DockerPermissionStrategy.Run
```
Now there is a test for that!

fix issue with broken docker entrypoint

---

build.sbt
src/main/scala/ai/metarank/mode/train/Train.scala
src/test/scala/ai/metarank/mode/TrainTest.scala

fixes https://github.com/metarank/metarank/issues/343

complain in train mode if dataset is empty

---

build.sbt

fix for https://github.com/metarank/metarank/issues/368

fix issue with err instead of ndcg in logs

---

build.sbt
doc/features/text.md
project/Deps.scala
src/main/scala/ai/metarank/FeatureMapping.scala
src/main/scala/ai/metarank/feature/BaseFeature.scala
src/main/scala/ai/metarank/feature/FieldMatchFeature.scala
src/main/scala/ai/metarank/feature/matcher/FieldMatcher.scala
src/main/scala/ai/metarank/feature/matcher/NgramMatcher.scala
src/main/scala/ai/metarank/feature/matcher/TermMatcher.scala
src/main/scala/ai/metarank/model/MValue.scala
src/main/scala/ai/metarank/util/TextAnalyzer.scala
src/test/scala/ai/metarank/feature/FieldMatchFeatureTest.scala
src/test/scala/ai/metarank/feature/matcher/NgramMatcherTest.scala
src/test/scala/ai/metarank/feature/matcher/TermMatcherTest.scala
src/test/scala/ai/metarank/util/DatasetGen.scala
src/test/scala/ai/metarank/util/TextAnalyzerTest.scala

a fix for https://github.com/metarank/metarank/issues/345

support field_match over terms

---

doc/xx_event_schema.md

Just my 5 cents. Like the project.

minor text improvements

---

doc/README.md
doc/features/generic.md
doc/features/scalar.md
doc/scopes.md

This is actually a copy-pasted snippet from https://medium.com/metarank/personalizing-recommendations-with-metarank-f2644112536b with some minor tweaks.

add doc about supported scopes

---

doc/features/datetime.md

A fix for https://github.com/metarank/metarank/issues/399

mention day_of_week in local_time extractor docs

---

doc/README.md
doc/deploy/docker.md
doc/supported-platforms.md

fixes https://github.com/metarank/metarank/issues/402

doc about supported platforms

---

doc/data-sources.md
src/main/scala/ai/metarank/config/EventSourceConfig.scala
src/main/scala/ai/metarank/source/EventSource.scala
src/main/scala/ai/metarank/source/FileEventSource.scala
src/test/scala/ai/metarank/config/EventSourceConfigTest.scala
src/test/scala/ai/metarank/mode/FileEventSourceTest.scala
src/test/scala/ai/metarank/source/FileEventSourceTest.scala

fixes https://github.com/metarank/metarank/issues/455

Add offset options to file connector

---

build.sbt

fix for https://github.com/metarank/metarank/issues/392

mac m1 support

---

src/main/scala/ai/metarank/feature/BooleanFeature.scala
src/main/scala/ai/metarank/feature/FieldMatchFeature.scala
src/main/scala/ai/metarank/feature/InteractedWithFeature.scala
src/main/scala/ai/metarank/feature/InteractionCountFeature.scala
src/main/scala/ai/metarank/feature/ItemAgeFeature.scala
src/main/scala/ai/metarank/feature/LocalDateTimeFeature.scala
src/main/scala/ai/metarank/feature/NumberFeature.scala
src/main/scala/ai/metarank/feature/RateFeature.scala
src/main/scala/ai/metarank/feature/RefererFeature.scala
src/main/scala/ai/metarank/feature/RelevancyFeature.scala
src/main/scala/ai/metarank/feature/StringFeature.scala
src/main/scala/ai/metarank/feature/UserAgentFeature.scala
src/main/scala/ai/metarank/feature/WindowCountFeature.scala
src/main/scala/ai/metarank/feature/WordCountFeature.scala
src/test/scala/ai/metarank/config/FeatureSchemaTest.scala

a fix for https://github.com/metarank/metarank/issues/482

more descriptive error messages for feature definitions

---

.github/workflows/tests.yml

a fix for https://github.com/metarank/metarank/issues/411

add jvm 17 to build matrix

---

build.sbt
src/test/scala/ai/metarank/fstore/redis/RedisFeatureTest.scala
src/test/scala/ai/metarank/fstore/redis/RedisKVStoreTest.scala

fixes https://github.com/metarank/metarank/issues/516

remove unused dependencies

---

src/main/scala/ai/metarank/main/api/FeedbackApi.scala
src/main/scala/ai/metarank/main/api/RankApi.scala
src/main/scala/ai/metarank/model/Field.scala

fixes https://github.com/metarank/metarank/issues/520

api: more readable request-response logs

---

.github/workflows/integration.yml
src/test/resources/ranklens/config.yml

a fix for https://github.com/metarank/metarank/issues/528

shutdown pulsar after connection tests, but before e2e

---

src/main/scala/ai/metarank/main/api/RankApi.scala
src/main/scala/ai/metarank/model/RankResponse.scala
src/test/scala/ai/metarank/main/api/RankApiTest.scala

a fix for https://github.com/metarank/metarank/issues/555

API explain flag was broken

---

doc/feature-extractors.md
doc/persistence.md
src/main/scala/ai/metarank/config/StateStoreConfig.scala
src/test/scala/ai/metarank/config/StateStoreConfigTest.scala

fixes https://github.com/metarank/metarank/issues/535

Persistence docs

---

doc/configuration/data-sources.md
src/main/scala/ai/metarank/source/FileEventSource.scala
src/test/scala/ai/metarank/source/FileEventSourceTest.scala

fixes https://github.com/metarank/metarank/issues/578

Use proper file ordering

---

build.sbt
src/main/resources/logback.xml
src/main/scala/ai/metarank/main/Constants.scala
src/main/scala/ai/metarank/main/Main.scala
src/main/scala/ai/metarank/model/AnalyticsPayload.scala
src/main/scala/ai/metarank/util/AnalyticsReporter.scala
src/main/scala/ai/metarank/util/ErrorReporter.scala
src/main/scala/ai/metarank/util/Version.scala
src/main/scala/ai/metarank/validate/checks/EventOrderValidation.scala
src/main/scala/ai/metarank/validate/checks/EventTypesValidation.scala
src/main/scala/ai/metarank/validate/checks/FeatureOverMissingFieldValidation.scala
src/main/scala/ai/metarank/validate/checks/InteractionKeyValidation.scala
src/main/scala/ai/metarank/validate/checks/InteractionMetadataValidation.scala
src/main/scala/ai/metarank/validate/checks/InteractionPositionValidation.scala
src/main/scala/ai/metarank/validate/checks/InteractionTypeValidation.scala

fixes https://github.com/metarank/metarank/issues/598

Sentry integration

---

README.md
doc/_toc.md
doc/changelog.md

- updated blog links
- added more links to docs

Updated blog links

---

doc/_toc.md
doc/configuration/overview.md
src/main/scala/ai/metarank/config/CoreConfig.scala
src/main/scala/ai/metarank/main/Main.scala
src/main/scala/ai/metarank/util/Version.scala
src/main/scala/ai/metarank/util/analytics/AnalyticsReporter.scala

Disable analytics and error reporting in CI

---

src/main/scala/ai/metarank/main/Main.scala
src/main/scala/ai/metarank/main/command/Serve.scala
src/main/scala/ai/metarank/util/analytics/AnalyticsReporter.scala
src/main/scala/ai/metarank/util/analytics/ErrorReporter.scala

fixes https://github.com/metarank/metarank/issues/605

Print app version on start

---

project/Deps.scala
src/main/scala/ai/metarank/api/JsonChunk.scala
src/main/scala/ai/metarank/api/routes/TrainApi.scala
src/main/scala/ai/metarank/util/analytics/AnalyticsReporter.scala
src/test/scala/ai/metarank/main/api/FeedbackApiTest.scala
src/test/scala/ai/metarank/main/api/RankApiTest.scala

supersedes https://github.com/metarank/metarank/pull/596

bump http4s to 1.0.0-M36

---

src/main/scala/ai/metarank/model/Feature.scala
src/test/scala/ai/metarank/fstore/FreqEstimatorSuite.scala

fixes https://github.com/metarank/metarank/issues/614

make FreqEstimatorSuite less flaky

---

doc/cli.md
src/main/scala/ai/metarank/main/CliArgs.scala
src/main/scala/ai/metarank/main/command/Import.scala
src/main/scala/ai/metarank/main/command/Standalone.scala
src/main/scala/ai/metarank/main/command/Validate.scala
src/test/scala/ai/metarank/main/CliArgsTest.scala

fixes https://github.com/metarank/metarank/issues/630

expose --sort-by option in cli

---

build.sbt
doc/configuration/supported-ranking-models.md
src/main/scala/ai/metarank/config/ModelConfig.scala
src/main/scala/ai/metarank/rank/LambdaMARTModel.scala
src/test/scala/ai/metarank/config/ModelConfigTest.scala

add feature sampling for lmart model

---

src/main/scala/ai/metarank/fstore/redis/RedisClickthroughStore.scala
src/main/scala/ai/metarank/main/command/Import.scala
src/main/scala/ai/metarank/main/command/Standalone.scala

so no hacks in redis-ct-store implementation

use flush and end to sync redis

---

build.sbt
doc/installation.md
project/Deps.scala
src/main/scala/ai/metarank/main/CliArgs.scala

Enforce JDK 11, migrate to Lucene 9.4

Dependency bump

---

.scalafmt.conf
doc/cli.md
src/main/scala/ai/metarank/api/routes/TrainApi.scala
src/main/scala/ai/metarank/main/CliArgs.scala
src/main/scala/ai/metarank/main/command/Standalone.scala
src/main/scala/ai/metarank/main/command/Train.scala
src/main/scala/ai/metarank/main/command/util/StreamResource.scala
src/test/resources/ranklens/config.yml
src/test/scala/ai/metarank/e2e/RanklensTest.scala
src/test/scala/ai/metarank/main/CliArgsTest.scala
src/test/scala/ai/metarank/main/TrainTest.scala
src/test/scala/ai/metarank/model/AnalyticsPayloadTest.scala

It just dumps the CSV files into the dir as is.
We probably eventually need to implement selectable train/test strategy.

Training dataset export support

---

src/main/scala/ai/metarank/feature/NumberFeature.scala
src/main/scala/ai/metarank/main/command/autofeature/FieldStat.scala
src/main/scala/ai/metarank/main/command/autofeature/ItemFieldStat.scala
src/test/scala/ai/metarank/main/autofeature/ItemFieldStatTest.scala

a fix for https://github.com/metarank/metarank/issues/681

autofeature: num[] should be treated differently as just num

---

doc/configuration/features/scalar.md
src/main/scala/ai/metarank/FeatureMapping.scala
src/main/scala/ai/metarank/feature/NumVectorFeature.scala
src/main/scala/ai/metarank/model/FeatureSchema.scala
src/test/scala/ai/metarank/feature/NumVectorFeatureTest.scala
src/test/scala/ai/metarank/feature/NumberFeatureTest.scala

fixes https://github.com/metarank/metarank/issues/680
there will be a follow-up PR with the autofeature support

Vector feature extractor

---

src/main/scala/ai/metarank/api/routes/FeedbackApi.scala
src/main/scala/ai/metarank/fstore/redis/RedisPersistence.scala

fixes https://github.com/metarank/metarank/issues/698

add explicit sync on /feedback api call

---

.github/test_docker.sh
.github/workflows/integration.yml
build.sbt
run_quickstart.sh
src/main/scala/ai/metarank/config/Config.scala
src/test/resources/config/redis.yml
src/test/resources/config/stateless.yml
src/test/resources/config/wrong-ref.yml

So by default API was binding to 127.0.0.1 instead of 0.0.0.0, which surprised new users.

fix issue with improper iface being bound in docker

---

src/main/scala/ai/metarank/fstore/ClickthroughStore.scala
src/main/scala/ai/metarank/fstore/clickthrough/DiscardClickthroughStore.scala

So it just drops the clickthroughs.

support discard clickthrough store

---

build.sbt
src/test/scala/ai/metarank/tool/StaticScoreTool.scala

Useful when you want to have a non-personalized set of static scores, which you can use later without metarank. The tool itself is not that much documented and more intended for an internal use, but it maybe useful for someone else :)

add static-score tool

---

src/main/scala/ai/metarank/main/CliArgs.scala
src/main/scala/ai/metarank/main/Sort.scala
src/test/scala/ai/metarank/main/SortTest.scala

Fixes https://github.com/metarank/metarank/issues/744

add a check for sort in==out

---

src/main/scala/ai/metarank/main/Sort.scala
src/test/scala/ai/metarank/main/SortTest.scala

fixes https://github.com/metarank/metarank/issues/741

make sort accept gzipped files

---

deploy/kubernetes/templates/deployment.yaml
deploy/kubernetes/values.yaml
doc/configuration/persistence.md
src/main/scala/ai/metarank/config/Config.scala
src/main/scala/ai/metarank/config/ConfigEnvSubst.scala
src/main/scala/ai/metarank/config/CoreConfig.scala
src/main/scala/ai/metarank/main/Main.scala
src/test/scala/ai/metarank/config/ConfigEnvSubstTest.scala
src/test/scala/ai/metarank/e2e/RanklensFileCtsTest.scala
src/test/scala/ai/metarank/e2e/RanklensTest.scala
src/test/scala/ai/metarank/util/benchmark/LatencyBenchmark.scala

So you don't need to hardcode passwords into the config.
fixes https://github.com/metarank/metarank/issues/766

Redis auth env var override

---

build.sbt
doc/_toc.md
doc/api.md
doc/configuration/overview.md
doc/configuration/sample-config.yml
doc/deploy/deployment-overview.md
doc/deploy/prometheus.md
project/Deps.scala
src/main/scala/ai/metarank/api/routes/FeedbackApi.scala
src/main/scala/ai/metarank/api/routes/MetricsApi.scala
src/main/scala/ai/metarank/api/routes/RankApi.scala
src/main/scala/ai/metarank/flow/MetarankFlow.scala
src/main/scala/ai/metarank/main/command/Serve.scala
src/main/scala/ai/metarank/util/analytics/Metrics.scala
src/test/scala/ai/metarank/main/api/MetricsApiTest.scala

Fixes https://github.com/metarank/metarank/issues/561

prom export support

---

src/main/scala/ai/metarank/FeatureMapping.scala
src/main/scala/ai/metarank/feature/RandomFeature.scala
src/main/scala/ai/metarank/model/AnalyticsPayload.scala
src/main/scala/ai/metarank/model/FeatureSchema.scala

random feature

---

src/main/scala/ai/metarank/model/EventId.scala
src/test/scala/ai/metarank/tool/MSRDPrep.scala

The dataset: https://github.com/metarank/msrd

MSRD dataset importer

---

src/main/scala/ai/metarank/flow/FeatureValueFlow.scala
src/main/scala/ai/metarank/fstore/redis/RedisPersistence.scala
src/main/scala/ai/metarank/fstore/redis/RedisScalarFeature.scala
src/main/scala/ai/metarank/model/Scope.scala

Fix for a memleak on a large dataset import

use proper cache invalidation strategy for cts buffer

---

src/main/scala/ai/metarank/flow/ClickthroughJoinBuffer.scala
src/main/scala/ai/metarank/main/command/Import.scala
src/main/scala/ai/metarank/main/command/Standalone.scala
src/test/scala/ai/metarank/e2e/RanklensFileCtsTest.scala
src/test/scala/ai/metarank/e2e/RanklensTest.scala
src/test/scala/ai/metarank/flow/ClickthroughJoinBufferTest.scala
src/test/scala/ai/metarank/flow/MetarankFlowTest.scala
src/test/scala/ai/metarank/main/ExportTest.scala
src/test/scala/ai/metarank/main/TrainTest.scala
src/test/scala/ai/metarank/main/api/TrainApiTest.scala

Do not reinvent the lru cache, use caffeine

better cts buffer impl

---

src/main/scala/ai/metarank/feature/RateFeature.scala
src/main/scala/ai/metarank/flow/ClickthroughJoinBuffer.scala
src/main/scala/ai/metarank/flow/MetarankFlow.scala
src/test/scala/ai/metarank/flow/MetarankFlowTest.scala
src/test/scala/ai/metarank/util/DoubleNaNEquality.scala

So you don't need to make flushall at the end of import

flush cts buffer on stream completion automatically

---

project/Deps.scala

There may be some netty issues

bump aws sdk to 2.19

---

src/main/scala/ai/metarank/fstore/file/client/RocksDBClient.scala

not sure that it's about direct io, fixes #847

fix flaky FileStatsEstimatorTest

---

src/main/scala/ai/metarank/validate/checks/FeatureOverMissingFieldValidation.scala
src/test/scala/ai/metarank/validate/FeatureOverMissingFieldValidationTest.scala

a fix for https://github.com/metarank/metarank/issues/849

fix validation for item.relevancy fields

---

src/main/scala/ai/metarank/ml/Predictor.scala
src/main/scala/ai/metarank/ml/rank/LambdaMARTRanker.scala
src/main/scala/ai/metarank/model/ClickthroughValues.scala
src/test/scala/ai/metarank/ml/rank/LambdaMARTRankerTest.scala

a fix for https://github.com/metarank/metarank/issues/861 (but not complete, there's a bunch of other issues to fix)

lmart model should correctly handle no clickthroughts case

---

src/main/scala/ai/metarank/fstore/file/client/RocksDBClient.scala
src/test/scala/ai/metarank/fstore/file/FileFreqEstimatorTest.scala

fixes https://github.com/metarank/metarank/issues/874

fix FileFreqEstimatorTest being flaky

---

.github/workflows/tests.yml

As azure ubuntu mirror is down

use FBCDN ubuntu mirror for redis on CI

---

src/main/scala/ai/metarank/ml/Model.scala
src/main/scala/ai/metarank/ml/rank/LambdaMARTRanker.scala

fixes https://github.com/metarank/metarank/issues/869

print ndcg before/after training

---

src/main/scala/ai/metarank/fstore/file/FilePersistence.scala
src/main/scala/ai/metarank/fstore/file/client/FileClient.scala
src/main/scala/ai/metarank/fstore/file/client/MapDBClient.scala
src/main/scala/ai/metarank/fstore/file/client/RocksDBClient.scala
src/main/scala/ai/metarank/main/command/Import.scala
src/test/resources/ranklens/config.yml
src/test/scala/ai/metarank/fstore/file/FileStatsEstimatorTest.scala
src/test/scala/ai/metarank/fstore/file/client/FileTestSuite.scala

fixes https://github.com/metarank/metarank/issues/858

Print per-feature mem usage on import

---

build.sbt
doc/configuration/overview.md
src/main/scala/ai/metarank/config/TrainConfig.scala
src/main/scala/ai/metarank/fstore/ClickthroughStore.scala
src/main/scala/ai/metarank/fstore/clickthrough/FileClickthroughStore.scala
src/main/scala/ai/metarank/fstore/redis/RedisKVStore.scala
src/test/resources/ranklens/config.yml
src/test/scala/ai/metarank/config/TrainConfigTest.scala
src/test/scala/ai/metarank/e2e/RanklensFileCtsTest.scala
src/test/scala/ai/metarank/fstore/clickthrough/FileClickthroughStoreTest.scala

fixes https://github.com/metarank/metarank/issues/891

do not append to cts file

---

doc/configuration/overview.md
doc/configuration/persistence.md
src/main/scala/ai/metarank/config/StateStoreConfig.scala
src/main/scala/ai/metarank/fstore/redis/RedisPersistence.scala
src/main/scala/ai/metarank/fstore/redis/client/RedisClient.scala

fixes https://github.com/metarank/metarank/issues/892

fix race condition in model upload

---

project/Deps.scala
src/test/scala/ai/metarank/config/FeatureSchemaTest.scala

update circe to 0.14.4

---

src/main/scala/ai/metarank/fstore/redis/RedisKVStore.scala

fixes https://github.com/metarank/metarank/issues/900

enable batching in kvstore redis sink

---

src/main/scala/ai/metarank/flow/ClickthroughJoinBuffer.scala

As we're just removing it later anyway.

do not queue empty ranking for flushing

---

src/main/scala/ai/metarank/ml/rank/LambdaMARTRanker.scala
src/test/scala/ai/metarank/ml/rank/LambdaMARTRankerTest.scala

fixes https://github.com/metarank/metarank/issues/918

check for too large dataset size

---

doc/configuration/supported-ranking-models.md
src/main/scala/ai/metarank/config/Selector.scala
src/main/scala/ai/metarank/ml/rank/LambdaMARTRanker.scala
src/test/scala/ai/metarank/config/SelectorTest.scala
src/test/scala/ai/metarank/config/SelectorYamlTest.scala

To filter out events with too deep clicks

add max-interaction-position event selector

---

src/main/scala/ai/metarank/feature/StringFeature.scala
src/test/scala/ai/metarank/feature/StringFeatureTest.scala

fixes https://github.com/metarank/metarank/issues/946

string feature support for ranking.field

---

build_docker.sh

fixes https://github.com/metarank/metarank/issues/953

fix dockerhub latest tag pointing to all images

---

src/main/scala/ai/metarank/feature/BooleanFeature.scala
src/main/scala/ai/metarank/feature/NumberFeature.scala
src/main/scala/ai/metarank/feature/StringFeature.scala
src/main/scala/ai/metarank/main/command/autofeature/rules/NumericalFeatureRule.scala
src/main/scala/ai/metarank/main/command/autofeature/rules/StringFeatureRule.scala
src/test/scala/ai/metarank/feature/BooleanFeatureTest.scala
src/test/scala/ai/metarank/feature/NumberFeatureTest.scala
src/test/scala/ai/metarank/feature/StringFeatureTest.scala
src/test/scala/ai/metarank/main/AutofeatureTest.scala
src/test/scala/ai/metarank/main/autofeature/rule/NumericalFeatureRuleTest.scala
src/test/scala/ai/metarank/main/autofeature/rule/StringFeatureRuleTest.scala
src/test/scala/ai/metarank/validate/FeatureOverMissingFieldValidationTest.scala
src/test/scala/ai/metarank/validate/StringValuesValidationTest.scala

a fix for https://github.com/metarank/metarank/issues/956

scalar fields config format mismatch with docs

---

src/main/scala/ai/metarank/FeatureMapping.scala
src/main/scala/ai/metarank/config/Config.scala
src/test/resources/config/similar-recs.yml
src/test/scala/ai/metarank/config/ConfigYamlTest.scala
src/test/scala/ai/metarank/feature/FeatureTest.scala
src/test/scala/ai/metarank/flow/ClickthroughQueryTest.scala
src/test/scala/ai/metarank/flow/MetarankFlowTest.scala
src/test/scala/ai/metarank/util/FeatureMappingTest.scala
src/test/scala/ai/metarank/util/RandomDataset.scala
src/test/scala/ai/metarank/util/TestConfig.scala
src/test/scala/ai/metarank/util/TestFeatureMapping.scala
src/test/scala/ai/metarank/util/TestSchema.scala
src/test/scala/ai/metarank/validate/FeatureOverMissingFieldValidationTest.scala
src/test/scala/ai/metarank/validate/StringValuesValidationTest.scala

fixes https://github.com/metarank/metarank/issues/957

allow empty features in config

---

src/main/scala/ai/metarank/FeatureMapping.scala
src/main/scala/ai/metarank/flow/ClickthroughJoinBuffer.scala
src/test/scala/ai/metarank/flow/ClickthroughJoinBufferTest.scala
src/test/scala/ai/metarank/util/TestFeatureMapping.scala

fixes https://github.com/metarank/metarank/issues/958

Fix crash on no reranker

---

.scala-steward.conf

As otherwise scala-steward makes the PR every 2 days

less frequent dep update for aws-sdk

---

doc/configuration/features/diversity.md
src/main/scala/ai/metarank/feature/DiversityFeature.scala
src/test/scala/ai/metarank/feature/DiversityFeatureTest.scala

fixes https://github.com/metarank/metarank/issues/966

trim to top-N items for diversity extractor

---

doc/api.md
doc/event-schema.md
doc/guide/_index.md
src/main/scala/ai/metarank/flow/ClickthroughQuery.scala
src/main/scala/ai/metarank/flow/TrainBuffer.scala
src/main/scala/ai/metarank/fstore/codec/impl/ClickthroughCodec.scala
src/main/scala/ai/metarank/fstore/codec/impl/DoubleArrayCodec.scala
src/main/scala/ai/metarank/fstore/codec/impl/FieldCodec.scala
src/main/scala/ai/metarank/fstore/codec/impl/ItemIdCodec.scala
src/main/scala/ai/metarank/fstore/codec/impl/ItemValueCodec.scala
src/main/scala/ai/metarank/fstore/codec/impl/MValueCodec.scala
src/main/scala/ai/metarank/fstore/codec/impl/SessionIdCodec.scala
src/main/scala/ai/metarank/fstore/codec/impl/TrainValuesCodec.scala
src/main/scala/ai/metarank/fstore/codec/impl/TypedIntCodec.scala
src/main/scala/ai/metarank/model/Clickthrough.scala
src/main/scala/ai/metarank/model/Event.scala
src/test/resources/codec/ctv-v3.bin
src/test/scala/ai/metarank/flow/ClickthroughQueryTest.scala
src/test/scala/ai/metarank/flow/TrainBufferTest.scala
src/test/scala/ai/metarank/fstore/codec/impl/TrainValuesCodecTest.scala

fixes https://github.com/metarank/metarank/issues/804

explicit relevance judgments support

---

doc/cli.md
doc/configuration/features/text.md
src/main/scala/ai/metarank/feature/FieldMatchFeature.scala
src/main/scala/ai/metarank/feature/matcher/BM25Matcher.scala
src/main/scala/ai/metarank/feature/matcher/FieldMatcher.scala
src/main/scala/ai/metarank/main/CliArgs.scala
src/main/scala/ai/metarank/main/Main.scala
src/main/scala/ai/metarank/main/command/TermFreq.scala
src/main/scala/ai/metarank/model/AnalyticsPayload.scala
src/main/scala/ai/metarank/model/FeatureSchema.scala
src/main/scala/ai/metarank/util/TextAnalyzer.scala
src/test/resources/ranklens/config.yml
src/test/scala/ai/metarank/feature/FieldMatchFeatureTest.scala
src/test/scala/ai/metarank/feature/matcher/BM25MatcherTest.scala
src/test/scala/ai/metarank/main/TermFreqDicTest.scala
src/test/scala/ai/metarank/util/RanklensEvents.scala

So we can be on par with ES-LTR :)

BM25 field matching support

---

src/main/scala/ai/metarank/ml/onnx/SBERT.scala

Forgetting to call `.close()` can cost you gigs!

fix native memory leak in ONNX inference

---

src/main/scala/ai/metarank/flow/TrainBuffer.scala

To save mem/disk when there's no recommender model.

emit user/info train events only when needed

---

src/main/scala/ai/metarank/main/command/Serve.scala

As it was disabled in the main api config

expose /inference api

---

build.sbt
src/main/scala/ai/metarank/feature/FieldMatchBiencoderFeature.scala
src/main/scala/ai/metarank/feature/FieldMatchCrossEncoderFeature.scala
src/main/scala/ai/metarank/ml/onnx/encoder/EncoderConfig.scala
src/main/scala/ai/metarank/ml/onnx/sbert/OnnxBiEncoder.scala
src/main/scala/ai/metarank/ml/onnx/sbert/OnnxCrossEncoder.scala
src/main/scala/ai/metarank/ml/onnx/sbert/OnnxSession.scala
src/main/scala/ai/metarank/ml/recommend/BertSemanticRecommender.scala
src/test/scala/ai/metarank/ml/onnx/sbert/OnnxCrossEncoderTest.scala

A fix for https://github.com/metarank/metarank/issues/1110 and https://huggingface.co/metarank/multilingual-e5-small

use DJL tokenizers for HF tokenization support

---

src/main/scala/ai/metarank/main/CliArgs.scala

fixes https://github.com/metarank/metarank/issues/1170

add check for data=out on sort

---

src/main/scala/ai/metarank/main/CliArgs.scala
src/test/scala/ai/metarank/main/CliArgsTest.scala

fixes https://github.com/metarank/metarank/issues/1169

add check for termfreq command that out file does not exist

---

src/main/scala/ai/metarank/validate/checks/InteractionPositionValidation.scala
src/test/scala/ai/metarank/validate/InteractionPositionValidationTest.scala

fixes https://github.com/metarank/metarank/issues/1191

fix validate crash on clicks on non-existent ranking

---

src/main/scala/ai/metarank/ml/rank/LambdaMARTRanker.scala
src/test/scala/ai/metarank/config/ModelConfigTest.scala

fixes https://github.com/metarank/metarank/issues/1188

do not allow to use reserved feature names used by rocksdb backend

---

src/main/scala/ai/metarank/model/AnalyticsPayload.scala

fixes https://github.com/metarank/metarank/issues/1121

fix match error on analytics payload with unknown feature type

---

doc/configuration/supported-ranking-models.md
src/main/scala/ai/metarank/config/ConfigValidations.scala
src/main/scala/ai/metarank/ml/rank/LambdaMARTRanker.scala
src/main/scala/ai/metarank/model/AnalyticsPayload.scala
src/main/scala/ai/metarank/validate/checks/InteractionTypeValidation.scala
src/test/scala/ai/metarank/config/ModelConfigTest.scala

fixes https://github.com/metarank/metarank/issues/1222

support custom eval metric names

---

src/main/scala/ai/metarank/fstore/EventTicker.scala
src/main/scala/ai/metarank/fstore/cache/CachedModelStore.scala
src/main/scala/ai/metarank/fstore/redis/RedisPersistence.scala
src/main/scala/ai/metarank/ml/Model.scala
src/main/scala/ai/metarank/ml/rank/LambdaMARTRanker.scala
src/test/scala/ai/metarank/fstore/cached/CachedModelStoreTest.scala

fixes https://github.com/metarank/metarank/issues/1257

fix native memleak in model cache

---

build.sbt
src/main/scala/ai/metarank/fstore/cache/CachedModelStore.scala
src/main/scala/ai/metarank/fstore/file/FileModelStore.scala
src/main/scala/ai/metarank/ml/Model.scala
src/main/scala/ai/metarank/ml/rank/LambdaMARTRanker.scala

So in a case when booster is closed, we don't crash the JVM

add guards for closed booster

---

src/main/scala/ai/metarank/config/InputConfig.scala
src/main/scala/ai/metarank/source/KinesisSource.scala

add retry in case of broken iterator for kinesis
