build.sbt, project/Deps.scala, src/main/scala/ai/metarank/flow/EventStateJoin.scala, src/main/scala/ai/metarank/mode/TypeInfos.scala, src/main/scala/ai/metarank/mode/bootstrap/Bootstrap.scala, src/main/scala/ai/metarank/mode/inference/FeedbackFlow.scala, src/main/scala/ai/metarank/mode/inference/Inference.scala, src/main/scala/ai/metarank/mode/inference/InferenceCmdline.scala, src/main/scala/ai/metarank/mode/upload/Upload.scala, src/main/scala/ai/metarank/source/LocalDirSource.scala
Stateful features were expecting to see historical state from the past. But we forgot to add savepoint-restore support for it, so after the restore all the past state was missing till someone sent a metadata update message.
Now we also store it in the savepoint.
=> Fix bug with missing join state

README.md, src/main/scala/ai/metarank/mode/inference/Inference.scala, src/main/scala/ai/metarank/mode/inference/api/FeedbackApi.scala, src/main/scala/ai/metarank/source/LocalDirSource.scala, src/test/scala/ai/metarank/ingest/LocalDirSourceTest.scala
We found that calling metarank `/feedback` route in parallel in multiple threads may cause a race condition in a queue implementation between http api and flink. Here we make it work properly:
* Writer is now a Resource
* each write call is IO and multiple IOs are scheduled in a way not to break each other
* autoincremented id of event is now updated atomically.
=> fix race in feedback file sink-source

src/main/scala/ai/metarank/mode/inference/Inference.scala
Hello and thank you for interesting recommendation service!
I organized code a bit to avoid nesting `Resource#use` because nesting resources can cause leak.
Although I don't think it is the case with Inference implementation,
I think this change will prevent us from having problem finding error
caused by misuse of Resource.
> Constructing a new Resource inside the body of a Resource#use can lead to memory leaks as the outer resource is not finalized until after the inner resource is released.
https://typelevel.org/cats-effect/docs/std/hotswap
In addition, I changed `mapping <- IO {...}` to `IO.pure {...}` as
`FeatureMapping.fromFeatureSchema` does not seem to invoke IO effect or throw error.
=> avoid nesting resource.use

src/main/scala/ai/metarank/mode/bootstrap/Bootstrap.scala
Bootstrap job was forcing the file prefix all the time, and in theory we can use hdfs and s3 ones.
=> do not use file:// prefix for used paths

.github/workflows/scala.yml, build.sbt, run_e2e.sh, src/main/scala/ai/metarank/config/Config.scala, src/main/scala/ai/metarank/mode/AsyncFlinkJob.scala, src/main/scala/ai/metarank/mode/FileLoader.scala, src/main/scala/ai/metarank/mode/bootstrap/Bootstrap.scala, src/main/scala/ai/metarank/mode/bootstrap/BootstrapCmdline.scala, src/main/scala/ai/metarank/mode/inference/FeedbackFlow.scala, src/main/scala/ai/metarank/mode/inference/Inference.scala, src/main/scala/ai/metarank/mode/inference/RedisEndpoint.scala, src/main/scala/ai/metarank/mode/upload/Upload.scala, src/main/scala/ai/metarank/mode/upload/UploadCmdline.scala, src/test/resources/ranklens/config.yml
This PR also streamlines dir handling in command-line args and fixes https://github.com/metarank/metarank/issues/310
=> Add e2e test for a ranklens tutorial

project/Deps.scala, run_e2e.sh, src/main/scala/ai/metarank/mode/TypeInfos.scala, src/test/scala/ai/metarank/mode/BootstrapSavepointTest.scala
So the NPE issue in https://github.com/metarank/metarank/issues/310 is related to some bug in flink happened in upgrade to https://github.com/metarank/metarank/pull/304. I was not able to find something related in flink's jira but in 1.15 the vulnerable part of the code was completely rewritten and has no such issue at all.
And the recent e2e test ironically made to catch this type of issue was written in bash was ignoring intermediate errors. So this PR:
* downgrades flink to 1.14.2 (snapshot of 1.15 also works, but it's not yet even RC), so NPE is gone
* e2e test is modified to handle intermediate errors (`set -e` ftw!)
* there is a reproducer test with snapshot management just in case if someone upgrades flink to 1.14.3+
=> downgrade flink to 1.14.2 due to NPE in state api

build.sbt
Flink already has transitive one, and it's always better to rely on a transitive one.
=> remove explicit guava dependency

.github/workflows/scala.yml, run_e2e.sh, src/main/scala/ai/metarank/mode/AsyncFlinkJob.scala, src/main/scala/ai/metarank/mode/bootstrap/Bootstrap.scala, src/main/scala/ai/metarank/mode/inference/Inference.scala, src/main/scala/ai/metarank/mode/upload/Upload.scala, src/main/scala/ai/metarank/mode/upload/UploadCmdline.scala, src/test/scala/ai/metarank/mode/AsyncFlinkJobTest.scala
When we run finite flink jobs within the cats.Resource, we always explicitly close it. 
The issue is when the job is finite (like the upload subtask, when there is a finite set of input files), the job successfully transitioned to a `FINISHED` state, and when we call `cluster.terminate` over a closed job, we get an error like in https://github.com/metarank/metarank/issues/310
In this PR:
* we check for the job status before terminating it, and not terminating already closed jobs
* test for finite jobs run using FlinkAsyncJobs
* e2e test updated to run a separate upload subtask and not to rely on a bundled inference one with inmem redis
* CI now has a redis container on the side
=> do not spit job close errors on finite flink jobs

doc/03_configuration.md, doc/features/counters.md, doc/tutorial_ranklens.md, doc/xx_api_schema.md, doc/xx_event_schema.md, src/main/scala/ai/metarank/mode/inference/api/RankApi.scala, src/main/scala/ai/metarank/model/Event.scala, src/main/scala/ai/metarank/source/FileEventSource.scala, src/test/scala/ai/metarank/model/EventJsonTest.scala
As it is marked optional in docs, but seems to be required in the schema.
=> make tenant field optional

src/main/scala/ai/metarank/mode/inference/InferenceCmdline.scala
We were binding to `::` and in docker it's sometimes problematic to have ipv6 enabled.
a fix for https://github.com/metarank/metarank/issues/366
=> bind to all ipv4 ifaces by default

src/main/resources/logback.xml, src/main/scala/ai/metarank/flow/EventProcessFunction.scala, src/main/scala/ai/metarank/mode/AsyncFlinkJob.scala, src/main/scala/ai/metarank/mode/bootstrap/Bootstrap.scala, src/main/scala/ai/metarank/mode/inference/FeedbackFlow.scala, src/main/scala/ai/metarank/mode/inference/FlinkMinicluster.scala, src/main/scala/ai/metarank/mode/inference/Inference.scala, src/main/scala/ai/metarank/mode/inference/RedisEndpoint.scala, src/main/scala/ai/metarank/mode/inference/api/FeedbackApi.scala, src/main/scala/ai/metarank/source/LocalDirSource.scala, src/test/scala/ai/metarank/e2e/RanklensTest.scala
So the inference job contained more stateful operators than the savepoint and failed to start. But we disabled flink logging, so noone noticed.
=> fix bug with non-restoreable savepoint

doc/03_configuration.md, doc/api_schema.md, doc/event_schema.md, src/main/scala/ai/metarank/feature/BaseFeature.scala, src/main/scala/ai/metarank/flow/ImpressionInjectFunction.scala, src/main/scala/ai/metarank/mode/bootstrap/Bootstrap.scala, src/main/scala/ai/metarank/mode/validate/EventFileValidator.scala, src/main/scala/ai/metarank/model/Event.scala, src/main/scala/ai/metarank/model/FeatureScope.scala, src/test/scala/ai/metarank/e2e/RanklensTest.scala, src/test/scala/ai/metarank/feature/InteractedWithFeatureTest.scala, src/test/scala/ai/metarank/feature/InteractionCountTest.scala, src/test/scala/ai/metarank/feature/StringFeatureTest.scala, src/test/scala/ai/metarank/feature/UserAgentFeatureTest.scala, src/test/scala/ai/metarank/flow/ClickthroughJoinFunctionTest.scala, src/test/scala/ai/metarank/flow/ImpressionInjectFunctionTest.scala, src/test/scala/ai/metarank/model/EventJsonTest.scala, src/test/scala/ai/metarank/util/RanklensDatasetGenerator.scala, src/test/scala/ai/metarank/util/TestInteractionEvent.scala, src/test/scala/ai/metarank/util/TestRankingEvent.scala
Fixes https://github.com/metarank/metarank/issues/415 and https://github.com/metarank/metarank/issues/414
=> make user/session/ranking fields in event schema optional

doc/sample-config.yml, src/main/scala/ai/metarank/config/BootstrapConfig.scala, src/main/scala/ai/metarank/config/Config.scala, src/main/scala/ai/metarank/config/InferenceConfig.scala, src/main/scala/ai/metarank/mode/bootstrap/Bootstrap.scala, src/main/scala/ai/metarank/mode/inference/FeedbackFlow.scala, src/main/scala/ai/metarank/mode/inference/Inference.scala, src/test/scala/ai/metarank/config/ConfigYamlTest.scala, src/test/scala/ai/metarank/e2e/RanklensTest.scala, src/test/scala/ai/metarank/util/TestConfig.scala
a fix for https://github.com/metarank/metarank/issues/417
=> Make impression injection configurable

project/Deps.scala, src/it/scala/ai/metaranke2e/e2e/RanklensTest.scala, src/main/scala/ai/metarank/flow/DatasetSink.scala, src/main/scala/ai/metarank/flow/EventProcessFunction.scala, src/main/scala/ai/metarank/mode/bootstrap/Bootstrap.scala, src/main/scala/ai/metarank/mode/bootstrap/FieldUpdateCodec.scala, src/main/scala/ai/metarank/mode/inference/FeedbackFlow.scala, src/main/scala/ai/metarank/mode/inference/Inference.scala, src/main/scala/ai/metarank/mode/inference/RedisEndpoint.scala, src/main/scala/ai/metarank/mode/upload/Upload.scala, src/main/scala/ai/metarank/mode/upload/WindowBatchFunction.scala, src/main/scala/ai/metarank/source/FeatureValueWatermarkStrategy.scala, src/test/resources/ranklens/config.yml, src/test/scala/ai/metarank/api/RankApiTest.scala, src/test/scala/ai/metarank/mode/FieldUpdateCodecTest.scala, src/test/scala/ai/metarank/util/FlinkTest.scala, src/test/scala/ai/metarank/util/RandomFeatureStore.scala
This thing improves bootstrap performance a lot:
* we only store the latest field/feature/state entries (and not the full changelog): smaller bootstrap size (10x on ranklens)
* redis writer now has proper batching support
* xgboost/lightgbm dataset export now uses buffering and writes data in chunks
* fields for some reason were not part of the savepoint: now they are
=> Bootstrap performance work

src/main/scala/ai/metarank/FeatureMapping.scala, src/main/scala/ai/metarank/feature/BaseFeature.scala, src/main/scala/ai/metarank/feature/BooleanFeature.scala, src/main/scala/ai/metarank/feature/FieldMatchFeature.scala, src/main/scala/ai/metarank/feature/InteractedWithFeature.scala, src/main/scala/ai/metarank/feature/InteractionCountFeature.scala, src/main/scala/ai/metarank/feature/ItemAgeFeature.scala, src/main/scala/ai/metarank/feature/LocalDateTimeFeature.scala, src/main/scala/ai/metarank/feature/NumberFeature.scala, src/main/scala/ai/metarank/feature/RateFeature.scala, src/main/scala/ai/metarank/feature/RefererFeature.scala, src/main/scala/ai/metarank/feature/RelevancyFeature.scala, src/main/scala/ai/metarank/feature/StringFeature.scala, src/main/scala/ai/metarank/feature/UserAgentFeature.scala, src/main/scala/ai/metarank/feature/WindowInteractionCountFeature.scala, src/main/scala/ai/metarank/feature/WordCountFeature.scala, src/main/scala/ai/metarank/feature/ua/PlatformField.scala, src/main/scala/ai/metarank/flow/ClickthroughQuery.scala, src/main/scala/ai/metarank/model/Dimension.scala, src/main/scala/ai/metarank/model/MValue.scala, src/test/scala/ai/metarank/util/FeatureMappingTest.scala
So when we define something like this in config:
```yaml
- name: day_item_click_count
type: window_count
interaction: click
scope: item
bucket: 24h
periods: [60]
```
The dataset descriptor cannot distinguish between singular values (as their dimension is 1) and a vector value (with also a dimension of 1). The encoding may be different, so it should be separate. But it wasn't.
=> fix issue with crash on single-bucket window counters

doc/configuration/overview.md, doc/configuration/sample-config.yml, src/main/scala/ai/metarank/config/StateStoreConfig.scala, src/main/scala/ai/metarank/flow/MetarankFlow.scala, src/main/scala/ai/metarank/fstore/EventTicker.scala, src/main/scala/ai/metarank/fstore/Persistence.scala, src/main/scala/ai/metarank/fstore/memory/MemBoundedList.scala, src/main/scala/ai/metarank/fstore/memory/MemClickthroughStore.scala, src/main/scala/ai/metarank/fstore/memory/MemCounter.scala, src/main/scala/ai/metarank/fstore/memory/MemFreqEstimator.scala, src/main/scala/ai/metarank/fstore/memory/MemKVStore.scala, src/main/scala/ai/metarank/fstore/memory/MemMapFeature.scala, src/main/scala/ai/metarank/fstore/memory/MemModelStore.scala, src/main/scala/ai/metarank/fstore/memory/MemPeriodicCounter.scala, src/main/scala/ai/metarank/fstore/memory/MemPersistence.scala, src/main/scala/ai/metarank/fstore/memory/MemScalarFeature.scala, src/main/scala/ai/metarank/fstore/memory/MemStatsEstimator.scala, src/main/scala/ai/metarank/fstore/redis/RedisPersistence.scala, src/main/scala/ai/metarank/main/CliArgs.scala, src/main/scala/ai/metarank/main/command/Standalone.scala, src/test/scala/ai/metarank/fstore/memory/MemCounterTest.scala, src/test/scala/ai/metarank/main/CliArgsTest.scala, src/test/scala/ai/metarank/util/SyntheticRanklensDataset.scala
No the caching is much more granular:
* mem store properly obeys the feature TTL
* there is now a single state cache for redis store (and not per feature type, which is hard to control)
* fix issue with `--validation=false` flag not being parsed properly
* ranklens dataset generator to do permutations for synthetic data
=> Fix improper cache TTL expiration on data import

src/main/scala/ai/metarank/main/CliArgs.scala, src/main/scala/ai/metarank/main/command/Train.scala, src/test/scala/ai/metarank/main/CliArgsTest.scala, src/test/scala/ai/metarank/model/AnalyticsPayloadTest.scala
usability improvement: no need to set the option when it's only single model. no option = train all you have
=> make 'train --model' option optional

src/main/scala/ai/metarank/feature/FieldMatchFeature.scala, src/main/scala/ai/metarank/feature/matcher/TermMatcher.scala, src/test/scala/ai/metarank/feature/FieldMatchFeatureTest.scala
To reproduce, try to decode the following config snippet:
```yaml
- name: title_match
type: field_match
itemField: item.title // must be a string
rankingField: ranking.query // must be a string
method:
type: term // for now only ngram and term are supported
language: en // ISO-639-1 language code
```
=> fix config decoding error for field_match over terms

build.sbt, src/main/scala/ai/metarank/util/Version.scala, src/test/resources/testmanifest.mf, src/test/scala/ai/metarank/util/VersionTest.scala
It was relying on the in-jar MANIFEST.MF file, but openjdk on ubuntu replaced this file with java-atk-wrapper one.
=> fix version detect within docker

doc/howto/autofeature.md, src/main/scala/ai/metarank/main/CliArgs.scala, src/main/scala/ai/metarank/main/command/AutoFeature.scala, src/main/scala/ai/metarank/main/command/autofeature/rules/RuleSet.scala, src/main/scala/ai/metarank/main/command/autofeature/rules/StringFeatureRule.scala, src/test/scala/ai/metarank/main/AutofeatureTest.scala, src/test/scala/ai/metarank/main/autofeature/rule/StringFeatureRuleTest.scala
So you can control the amount of categories in the autofeature string category generator rule. As sometimes there's not that many of them.
=> cat-threshold cli arg

src/main/scala/ai/metarank/main/CliArgs.scala
fixes https://github.com/metarank/metarank/issues/742
Now it prints something like this:
```
java.lang.Exception: Path src/test/resources/ranklens/config.yml2 does not exist, but these files do:
- src/test/resources/ranklens/config.yml
- src/test/resources/ranklens/events
- src/test/resources/ranklens/ranklens.model
```
=> make pathExists validation error message less cryptic

src/main/scala/ai/metarank/flow/CheckOrderingPipe.scala
fixes https://github.com/metarank/metarank/issues/739
=> sort inline doc mentions --config option, which is not used anymore

src/main/scala/ai/metarank/model/Timestamp.scala, src/test/scala/ai/metarank/model/TimestampJsonTest.scala
So it will match behavior from docs: https://docs.metarank.ai/reference/event-schema/timestamp-formats
=> add tests for timestamp parser

src/main/scala/ai/metarank/fstore/clickthrough/FileClickthroughStore.scala, src/test/scala/ai/metarank/fstore/clickthrough/FileClickthroughStoreTest.scala
Looks like that click-through store local file is being over-written (and reset) on Metarank restart. When we open OutputStream, we don't mark it with `append=true`, so it resets it.
=> fix issue with cts file being overwritten

doc/configuration/persistence.md, src/main/scala/ai/metarank/fstore/redis/RedisPersistence.scala
Should fix an issue with GCP Memstore Redis, which does not support client-side cache invalidation.
=> disabled caching should not send an invalidation subscription to redis

.github/workflows/integration.yml, .github/workflows/tests.yml, deploy/kubernetes/values.yaml, deploy/metarank.sh, doc/deploy/docker.md, doc/deploy/kubernetes.md
So users can control the actual JVM mem usage. We also explicitly set heap size to 1g by default.
=> expose JVM_OPTS to env

src/main/scala/ai/metarank/flow/ImpressionInject.scala, src/test/scala/ai/metarank/flow/ImpressionInjectTest.scala
A fix for the following issue:
```
20:03:01.924 ERROR org.http4s.server.service-errors - Error servicing request: POST /feedback from 6.6.6.6
java.lang.UnsupportedOperationException: empty.max
at scala.collection.IterableOnceOps.max(IterableOnce.scala:978)
at scala.collection.IterableOnceOps.max$(IterableOnce.scala:976)
at scala.collection.AbstractIterable.max(Iterable.scala:933)
at ai.metarank.flow.ImpressionInject$.process(ImpressionInject.scala:18)
at ai.metarank.flow.MetarankFlow$.$anonfun$process$16(MetarankFlow.scala:40)
at scala.collection.immutable.List.flatMap(List.scala:293)
at ai.metarank.flow.MetarankFlow$.$anonfun$process$15(MetarankFlow.scala:40)
```
=> fix empty-max crash

src/main/scala/ai/metarank/fstore/redis/RedisModelStore.scala, src/main/scala/ai/metarank/ml/rank/LambdaMARTRanker.scala, src/test/resources/ranklens/config.yml, src/test/scala/ai/metarank/fstore/ModelStoreSuite.scala, src/test/scala/ai/metarank/fstore/file/FileStatsEstimatorTest.scala, src/test/scala/ai/metarank/fstore/memory/MemModelStoreTest.scala, src/test/scala/ai/metarank/fstore/redis/RedisModelStoreTest.scala
A fix for:
```
java.lang.Exception: unsupported bitstream version -74, please re-run train
at ai.metarank.ml.rank.LambdaMARTRanker$LambdaMARTPredictor.load(LambdaMARTRanker.scala:91)
at ai.metarank.fstore.redis.RedisModelStore.$anonfun$get$1(RedisModelStore.scala:35)
at map @ ai.metarank.fstore.redis.RedisModelStore.$anonfun$get$1(RedisModelStore.scala:28)
at apply @ ai.metarank.fstore.redis.client.RedisClient.get(RedisClient.scala:57)
at fromCompletableFuture @ ai.metarank.fstore.redis.RedisPersistence$.$anonfun$create$4(RedisPersistence.scala:169)
at map @ ai.metarank.fstore.redis.client.RedisClient.get(RedisClient.scala:57)
at flatMap @ ai.metarank.fstore.redis.RedisModelStore.get(RedisModelStore.scala:27)
at apply @ ai.metarank.fstore.memory.MemModelStore.get(MemModelStore.scala:13) …
```
=> fix crash on model load with unsupported bitstream error

src/main/scala/ai/metarank/fstore/redis/RedisPersistence.scala, src/main/scala/ai/metarank/fstore/redis/client/RedisClient.scala
So when pipelining is disabled, there's no point in flushing. A case for model upload.
=> make redis flush conditional of pipelining

src/main/scala/ai/metarank/main/command/Validate.scala, src/main/scala/ai/metarank/validate/checks/StringValuesValidation.scala, src/test/scala/ai/metarank/validate/StringValuesValidationTest.scala
So in a case if you configured the string feature extractor wrong, it will show unused values
=> string values validation

src/main/scala/ai/metarank/model/ItemValue.scala, src/main/scala/ai/metarank/model/MValue.scala
As it was over-using dynamism - now we short-circuited it altogether to native implementations.
=> add custom faster hashCode to ItemValue and MValue to speed-up mem store

build.sbt, src/main/scala/ai/metarank/ml/rank/LambdaMARTRanker.scala, src/test/scala/ai/metarank/util/TestQueryRequest.scala
It was resulting in a sub-optimal training on all the boosters when dataset was not sorted by query-id - which is like almost always.
=> fix issue with ndcg mismatch in booster and eval

src/main/scala/ai/metarank/main/command/autofeature/EventCountStat.scala, src/test/scala/ai/metarank/main/autofeature/model/LambdaMARTConfigGeneratorTest.scala
It was complaining on missing clicks.
=> Fix autofeature on explicit judgements

src/main/scala/ai/metarank/main/command/train/SplitStrategy.scala, src/main/scala/ai/metarank/ml/rank/LambdaMARTRanker.scala, src/main/scala/ai/metarank/model/QueryMetadata.scala, src/test/scala/ai/metarank/main/SplitStrategyTest.scala
So you can explicitly set which ranking goes to test and train.
Useful for the ESCI dataset.
=> add field split strategy

src/main/scala/ai/metarank/util/CSVStream.scala, src/test/scala/ai/metarank/util/CSVStreamTest.scala
So it will parse CSVs with embeddings of this format:
```
socks,2,3,4,5,6,7
""red"" socks,2,3,4,5,6,7
```
=> support RFC4180 CSV double-quotes

src/main/scala/ai/metarank/fstore/codec/impl/ScalarCodec.scala, src/test/scala/ai/metarank/fstore/redis/codec/impl/ScalarCodecTest.scala
We write byte length, and read a varint. When length > 128, then BOOM.
=> fix crash on scalar codec with long numeric lists

src/main/scala/ai/metarank/fstore/file/client/MapDBClient.scala, src/test/scala/ai/metarank/fstore/file/client/MapDBClientTest.scala
For the ESCI demo, where we're going to use the file state instead of redis - as it's easier to wrap in into docker
=> fix crash on reopening existing file state db

src/main/scala/ai/metarank/api/routes/inference/BiEncoderApi.scala, src/main/scala/ai/metarank/api/routes/inference/CrossEncoderApi.scala, src/main/scala/ai/metarank/config/Config.scala, src/main/scala/ai/metarank/main/command/Serve.scala, src/main/scala/ai/metarank/ml/onnx/ModelHandle.scala, src/test/scala/ai/metarank/config/ConfigInferenceTest.scala, src/test/scala/ai/metarank/main/api/BiEncoderApiTest.scala
So you don't need to re-define them again in the `inference` config section. This will also reuse the onnx session.
=> expose all bi/cross encoder features in the /inference endpoint by default

src/main/scala/ai/metarank/config/ApiConfig.scala, src/main/scala/ai/metarank/main/command/Serve.scala
A fix for a timeout issue on doing `/train` API call. A code authored by `Yuri` from slack.
=> set default api timeout to 5 minutes

src/main/scala/ai/metarank/fstore/codec/values/BinaryVCodec.scala
Hi,
This PR fixes a memory leak/heavy consumption of memory using the binary format with compression enabled.
We found a potential memory leak, when calling the /feedback API, with lots of data.
Symptom: Metarank eats the memory (defined with `-Xmx`) and is killed by the OOMKiller after some time.
Using the profiler, we found that the binary format with compression was consuming a lots of memory, and that the stream was actually not closed.
- We are sending ~200k events to /feedback in bulk on 10 events
- `-Xmx8g` (or more)
- Metarank is killed after ingesting ~3k events
Metarank is not killed and works perfectly fine with less memory! (`-Xmx1g`).
This is strange and funny! But why not :)
- version 0.7.2 (jar)
- JDK 11
- Redis
Config:
```yaml
state:
type: redis
host: localhost
port: 6379 …
```
=> fix: Metarank gets killed (oomkiller): not closed outputstream in binary format with compress enabled

src/main/scala/ai/metarank/fstore/file/FilePersistence.scala, src/main/scala/ai/metarank/fstore/file/client/DB.scala, src/main/scala/ai/metarank/fstore/file/client/FileClient.scala, src/main/scala/ai/metarank/fstore/file/client/MapDBClient.scala, src/main/scala/ai/metarank/fstore/file/client/RocksDBClient.scala, src/main/scala/ai/metarank/fstore/file/client/rocksdb/RocksDB.scala, src/test/scala/ai/metarank/fstore/file/FileTest.scala, src/test/scala/ai/metarank/fstore/file/client/MapDBClientTest.scala, src/test/scala/ai/metarank/fstore/file/client/RocksDBClientTest.scala
fixes https://github.com/metarank/metarank/issues/1178
also enables mapdb compaction at import end
=> fix file backend options are not used in init, trigger a rocksdb compaction on end

doc/configuration/feature-extractors.md, doc/configuration/features/generic.md
=> doc: remove relative_number as superceded by regular number

.github/compose-redis.yaml, doc/configuration/persistence.md, src/main/scala/ai/metarank/config/StateStoreConfig.scala, src/main/scala/ai/metarank/fstore/redis/RedisPersistence.scala
So now it prints a proper warning with an advice on what to do if got NOPERM for CLIENT TRACKING command.
Fixes https://github.com/metarank/metarank/issues/1225
=> GCP Memstore redis: add extra toggle to disable CLIENT TRACKING cache invalidation

.github/workflows/integration.yml
As GC Actions upgraded the ubuntu-22.04 image to a newer docker, and `docker-compose`  is now `docker compose`
=> ci: migrate to newer docker compose
